language: android
android:

  components:
    # Uncomment lines below whether you want
    # to use the latest version of Android SDK Tools.
    - platform-tools
    - tools

    # The version of the Build Tools used for your project.
    - build-tools-23.0.3

    # The version of the SDK Android used to compile your project.
    - android-23

    # Additional components.
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify, at least, one system image
    # whether you need to run the emulator during your tests.
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17

before_install:
    - chmod +x gradlew

# Emulator Management: Create, Start and Wait
before_script:
    - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script:
    ./gradlew clean testDebugUnitTest connectedDebugAndroidTest assembleDebug
